# This is the configuration file for the pipeline
# Input directory is the directory where the fastq/fasta files are located
# Empty string to use the current directory
input_directory: "reads/"
# Extension of the files to be processed
read_extension: ".fastq"
# CSV file with the metadata. The first column must contain the sample names (that is, the filename without the extension)
metadata: "metadata.csv"
# Uncomment to use different databases!
# SILVA database
database: "/Databases/emu-prebuilt/silva_database"
ranks: ["superkingdom", "phylum", "class", "order", "family", "genus", "species"]
# NCBI database
#database: "/Databases/emu-prebuilt/ncbi_database"
#ranks: ["species", "genus", "order", "class","phylum", "clade", "superkingdom", "subspecies", "species subgroup ", "species group"]
# UNITE (all)
#database: "/Databases/emu-prebuilt/unite-all"
#ranks: ["superkingdom", "phylum", "class", "order", "family", "genus", "species"]
# Number of threads per sample. It will determine the parallelization of the pipeline
threads_per_sample: 5
# Optional flags for the emu abundance command
emu_abundance_flags: "--type map-ont"