# This is the configuration file for the pipeline
# Input directory is the directory where the fastq/fasta files are located
# Empty string to use the current directory
input_directory: "reads/"
# Extension of the files to be processed
read_extension: ".fastq"
# CSV file with the metadata. The first column must contain the sample names (that is, the filename without the extension)
metadata: "metadata.csv"
# EMU database directory
database: "/Databases/emu-prebuilt/silva_database"
# Number of threads per sample. It will determine the parallelization of the pipeline
threads_per_sample: 5
# Optional flags for the emu abundance command
emu_abundance_flags: "--type map-ont"