# Directory with the reads in .fastq
reads_dir: "porechopped/"
# Metadata csv file with at least the columns sample_id,sample_name
# Please, find a template for this table in the cloned repo
metadata_tbl: "metadata.csv"
# Our default database SILVA
emu_database: "/Databases/emu-prebuilt/silva_database"
# EMU default database NCBI (notice it only works for one database)
#emu_database: "/Databases/emu-prebuilt/ncbi_database/" # Uncomment to use it


# Add here any optional flag to emu
# Uncomment to add flags
# emu_abundance:
#   - "--min-abundance 5"
